### ISSUE TITLE
Navigating to the next page on the Grants table results in an Internal Server Error

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/testnet#1129]
https://github.com/interledger/testnet/assets/60383558/e58c3e5f-7e5f-49a6-b4eb-1af49805f175

**Comment by Tymmmy** [comment]
Pagination is working ok, the problem is the new types added in Rafiki for Grants, for example Granted is no more, Finalized is the new one.

So we will add new types and the finalization reason also.
