### ISSUE TITLE
Exchange money and Transactions problems for other currencies 

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1209]
Looks like on rafiki.money the Exchange money buttton and Transactions are getting EXPIRED when we are dealing with other currencies then USD or EUR.
Please check for example SGD, HKD, RON etc...

**Comment by rico191013** [comment]
![Screenshot 1402-12-25 at 2 59 45 PM](https://github.com/interledger/testnet/assets/101926344/06cfe8b8-5ff6-4f37-9a06-cfdfd17ef94e)
The problem was related to the Rapyd wallet type, which had been fixed previously. It just requires updating the GCP.
