### ISSUE TITLE
Check UI Dark mode

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1235]
We should check all aspects of Testnet in Dark mode, and fix all issues. (Wallet ans Boutique)
For example the Onboarding has some  white spots (triangle), and also we could improve in the display on this in dark mode:
![Screenshot 2024-03-25 at 10 16 09](https://github.com/interledger/testnet/assets/117268143/40c0e5c5-560c-44b6-a8c6-953752487ab3)

EDIT - We will have another design in works for Test wallet and Test Boutique, that means that this story will be nullified

**Comment by Tymmmy** [comment]
@devcer will take a look

**Comment by devcer** [comment]
Hey @Tymmmy , You can assign this to me. I will work on this.

**Comment by Tymmmy** [comment]
Closed because of new designs upcoming

**Comment by Tymmmy** [comment]
Closed because of new designs upcoming
