### ISSUE TITLE
Interledger test wallet redesign

### ISSUE THREAD

**Issue by huijing** [interledger/testnet#1305]
Grantees are conflating Rafiki and rafiki.money (which is the URL for Interledger test wallet), and mistakenly thinking that they have to integrate the Interledger test wallet instead of Rafiki.

We have decided that by diverging the look and feel of Testnet from any of our actual products like Interledger Pay or Rafiki, people will be less inclined to confuse any of our testnet assets with Rafiki.

The key here is we are not making any functional or layout changes, we are only updating the following:
- Site colours
- Site logo
- Site font

Of course, due to the change in font, there might be some tweaks required to element widths or heights but this is really a pure theme change.

Please refer to this more detailed write-up explaining the rationale behind the new visual direction: https://docs.google.com/document/d/1oGq2TCnbD6zpWovwdDu5oKKsLzQjMw0er2aL6VJtjhA/edit

## New colour codes

Please see https://testnet-mockup.surge.sh/wallet/styleguide/

## Proposed interaction styles

For focus, hover and active styles, you can see them in action on the frontend mockups at https://testnet-mockup.surge.sh/wallet/. You need to toggle dark mode because the glows are only used on dark mode. The CSS code for the glow effects are also on https://testnet-mockup.surge.sh/wallet/styleguide/.

Again, because this was just to recreate the elements on the original test wallet, any of the padding and margin differences between the mock-up and the real code should be ignored. This Codepen is meant to show the hover states, focus states and active states, plus how the new colors look like applied on the existing elements.

## Attached asset files

![logo](https://github.com/interledger/testnet/assets/1461498/021b0fc9-6935-4c1e-9d7d-12a0de0a453c)

[dejavu-mono.zip](https://github.com/interledger/testnet/files/15005003/dejavu-mono.zip)

- [x] #1380 
- [x] #1381 
- [x] #1382 
- [x] #1383 
- [x] #1384 
- [x] #1385 
- [x] #1386 
- [x] #1387 
- [x] #1388 
- [x] #1389 
- [x] #1390 
- [x] #1392

**Comment by Tymmmy** [comment]
Done, needs to be deployed next week, and done :D
