### ISSUE TITLE
Onboarding - make it better

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1318]
- Account page

      1. When selecting account to change to “for your new EUR account” 
      2. When opening the account: “At least one payment pointer”
      3. “Your balance is currently $0” should be “your balance is currently €0”
      4. “To make your first transaction please add play money”

- Transfer page

      1. On the account onboarding, the icons should match or not be there at all
      2. Transfer send page: explain/onboard all of the input fields on the screen
      4. In the send/receive: explain “send” first in the onboarding text
      5. Reviewing payment details, remove the “... for now” sentence.
      6. Add an onboarding to the Request flow page
      7. Check if you can do a skip on Send and Request onboarding steps

**Comment by huijing** [comment]
I don't know if this will help, but as I was going through the on-boarding flow I took screenshots and potentially broke the flow:

https://docs.google.com/document/d/1XBumEy2fbA0EOMG7r4I4KlUfU91m7joI4m_iMuU0wBU/edit#bookmark=id.qufyyshr54u2

**Comment by Tymmmy** [comment]
> I don't know if this will help, but as I was going through the on-boarding flow I took screenshots and potentially broke the flow:
> 
> https://docs.google.com/document/d/1XBumEy2fbA0EOMG7r4I4KlUfU91m7joI4m_iMuU0wBU/edit#bookmark=id.qufyyshr54u2

I will check out the document, we will do some revamping of the Oboarding in the very near future...AKA when I have time :D
