### ISSUE TITLE
Web Monetization on Test Wallet

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1321]
Simplify the asset scale 9 vs asset scale 2  : 

- Getting rid of web monetization tab -every wallet address will be set scale 9, and display all in one tab
- (Every PP will have a corresponding PP for WM in the back?)
- Display as asset scale 2 and bellow or hover asset scale 9
- Every payment pointer will be default asset scale 9 (this makes it easier for ASEs to enable WM by default)
- How to send from asset scale 9 to asset scale 2? 
- The peering relationships will have to be over asset scale 9
- The transfer page should allow to be able to view asset scale 9 - Show asset scale 9s in list of send
- Figure out migration of current PPs in rafiki.money - we will not get rid of our current DB!!!

**Comment by sanducb** [comment]
Created the following tasks based on the requirements and further discussions with @beniaminmunteanu @raducristianpopa  @dragosp1011: 

Frontend: #1357
Backend: #1358, #1359

Will add more context after we clarify all the aspects about the Rafiki rate service usage and migration.

**Comment by Tymmmy** [comment]
In regards of the new Gatehub sandbox we need to integrate in order to replace Rapyd, and looks like assetscale 2 is the one that would be completely supported, we will bench this story, but take out the useful stuff akready inside it and apply to main code.
