### ISSUE TITLE
Grant interaction page text fix when it is NOT withdraw

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1324]
We need to change the text for grant interaction page: Access money and not Withdraw money on rafiki.money grant interaction page - web monetization and boutique instant buy grant.

For example when you buy normaly on boutique you have, which is correct:
![image](https://github.com/interledger/testnet/assets/117268143/813fbbe7-6f58-47ef-b630-11b17cf1a511)

When you set up One Click Buy in Boutiqe, the same message appears:
![image](https://github.com/interledger/testnet/assets/117268143/4797cdf3-d55e-44b7-86b8-8842117cc190)

Here is the problem, as this grant will not withdraw your money (ex. 2222$), the grant only has access to withdraw that amount of money when you buy with One Click Buy.
So we need to change here the interaction, and specify somehow if it is instant buy, then it is WITHDRAW MONEY, when it is recurring access granted, then it should be only the text ACCESS MONEY.

EDIT -
After further discussing with the team we decided the best approach would be to have a universal message to access account on every grant interaction.
SOmething similar to Fynbos:
<img width="331" alt="image" src="https://github.com/interledger/testnet/assets/117268143/3f9d97da-b15f-4a43-8cb9-2a91bd193fa9">

**Comment by raducristianpopa** [comment]
I do no think these should have different meaning. A grant doesn't "withdraw" the money, it only gives access to a specified amount.

**Comment by Tymmmy** [comment]
We discussed this in the workweek, a grant gives access when you set up one click buy and doesn't withdraw money, but it will withdraw money when you buy normally at checkout

**Comment by raducristianpopa** [comment]
> We discussed this in the workweek, a grant gives access when you set up one click buy and doesn't withdraw money, but it will withdraw money when you buy normally at checkout. @raducristianpopa

Still, when performing the checkout flow, we first ask the user to approve that specified amount. Money are withdrawn afterwards.
