### ISSUE TITLE
New domain names for Test Network

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1327]
EDIT - 
wallet.interledger-test.dev. ---> rafiki.money 
boutique.interledger-test.dev ---> rafiki.boutique 

We want to make a clear difference between Rafiki and Test Network.
In doing so we will have new domain name for the following

**Comment by golobitch** [comment]
@Tymmmy I need more info here:
* What should be the connector address?
    * connector.interledger.tech ?
* What should be the API url for try.interledger.tech/wallet ?
* What should be the API url for try.interledger.tech/shop ?
* What should be the URL for autopeer?
* What should be the URL for auth (current is auth.rafiki.money)
    * Proposed: `auth.interledger.tech`
* What should be the ILP address? (current ilp.rafiki.money)
    * Proposed: `ilp.interledger.tech`
* What should be the URL for admin (current admin.rafiki.money)

**Comment by dragosp1011** [comment]
How about we use `wallet.try.interledger.tech` for wallet related stuff and `shop.try.interledger.tech`.
So for api we will have `api.wallet.try.interledger.tech` and `api.shop.try.interledger.tech` respectively.

Maybe it make sense to remove `try` subdomain on this level to have the urls a bit shorter if this won't add confusion.

**Comment by golobitch** [comment]
My personal preference would be without try ... so basically just `wallet.interledger.tech` and `shop.interledger.tech`

For now, I will use following domains:
* `wallet.try.interledger.tech`
* `shop.try.interledger.tech`

**Comment by dragosp1011** [comment]
What should be the connector address?

- connector.try.interledger.tech

What should be the API url for try.interledger.tech/wallet ?

- api.wallet.try.interledger.tech

What should be the API url for try.interledger.tech/shop ?

- api.shop.try.interledger.tech

What should be the URL for autopeer?

- autopeer.try.interledger.tech

What should be the URL for auth (current is auth.rafiki.money)

- auth.try.interledger.tech

What should be the ILP address? (current ilp.rafiki.money)

- ilp.try.interledger.tech

What should be the URL for admin (current admin.rafiki.money)

- admin.try.interledger.tech

This is what I think. @raducristianpopa @beniaminmunteanu do you agree?

**Comment by golobitch** [comment]
@dragosp1011 we have a little bit of a problem here. In order to have both rafiki.money and rafiki.boutique running simultenously with try.interledger.tech we would need to spawn new containers due to some URLs that are defined in the env right?

for example, every frontend app has env variable that points to backend and they are set to api.rafiki.money and api.rafiki.boutique ... they will need to point now to api.wallet.try.interledger.tech and api.shop.try.interledger.tech

But also rafiki auth container would need to be new due to rafiki auth server domain, and ofc also backend.

Please advise on how to proceed.

**Comment by Tymmmy** [comment]
@dragosp1011 @golobitch we do need both to be running for now, the new site will be launched together with the new design. So not in the very near future, at least 2 months from now.

**Comment by dragosp1011** [comment]
@golobitch everything is in env variables so we will ned to update them.

@Tymmmy we will need to update the email templates as well to point to env variables as there are some hardcoded links

**Comment by Tymmmy** [comment]
Yes, email templated will all be updated also with new design in the near future

**Comment by Tymmmy** [comment]
@golobitch it has finaly been decided to have:

wallet.interledger-test.dev
boutique.interledger-test.dev

**Comment by Tymmmy** [comment]
Done
