### ISSUE TITLE
Implementing Open API

### ISSUE THREAD

**Issue by rico191013** [interledger/testnet#1341]
Implement Open API for Testnet Wallet backend and Testnet Boutique backend
Controllers: 
- [ ]  [wallet/account](https://github.com/interledger/testnet/issues/1334)
- [ ] [wallet/asset](https://github.com/interledger/testnet/issues/1335)
- [ ] [wallet/auth](https://github.com/interledger/testnet/issues/1336)
- [ ] [wallet/grant](https://github.com/interledger/testnet/issues/1337)
- [ ] [wallet/rapyd](https://github.com/interledger/testnet/issues/1338)
- [ ] [wallet/incomingPayment](https://github.com/interledger/testnet/issues/1340)

EDIT - we will close this issue and Share types accross Testnet. We will no longer implement Open API

**Comment by Tymmmy** [comment]
we will close this issue and Share types accross Testnet. We will no longer implement Open API
