### ISSUE TITLE
[FE] Asset scale 2 to asset scale 9

### ISSUE THREAD

**Issue by sanducb** [interledger/testnet#1357]
- [ ] Getting rid of WM tab - every wallet address will be set to scale 9, display all in one tab
- [ ] Display as asset scale 2 below or hover for asset scale 9
- [ ] The transfer page should allow viewing asset scale 9 -> show asset scale 9s in list of send

Related to #1358, #1359.

**Comment by raducristianpopa** [comment]
Closed. See details here -  https://github.com/interledger/testnet/issues/1321#issuecomment-2323915072
