### ISSUE TITLE
Migration plan - Asset scale 2 to asset scale 9

### ISSUE THREAD

**Issue by sanducb** [interledger/testnet#1359]
## Rafiki:
- [ ] Migrate wallet addresses from asset scale 2 to asset scale 9 in current production database
- [ ] Accounting related tables should also be migrated to asset scale 9
- [ ] **Optional**: Migrate everything to Tigerbeetle (if we want this, then this should be done first)
## Wallet backend:
- [ ] All accounts should have a virtual balance

Changes required by #1357

**Comment by raducristianpopa** [comment]
Closed. See details here -  https://github.com/interledger/testnet/issues/1321#issuecomment-2323915072
