### ISSUE TITLE
[Test Wallet - New Design] - add new images

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1380]
Add the new Layout images:
https://www.figma.com/design/b0Q8gZa5UXkSZEiEMilTwZ/Test-Wallet-Redesign?node-id=0-1&t=d2xT6n3TmhVZZjKp-0

https://drive.google.com/drive/folders/1gna_Z5RAQAOvnmXGbP84visALgD8JxCt

**Comment by raducristianpopa** [comment]
Closed by #1425.
