### ISSUE TITLE
[BUG] Developer Keys upload error

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1542]
### Steps to reproduce

1. Go to Settings -> Developer Keys
2. Click on a PPs Upload Key
3. Paste a Public key there, either a duplicate or a wrong key
4. Click on  Upload

### Expected result

We should have normal error messages displayed, not Internal Server Error

### Actual result

We receieve Internal Server Error for incorrect or duplicate Keys

### Screenshots or videos

<img width="430" alt="image" src="https://github.com/user-attachments/assets/6c15cf30-f634-4ea7-bc4f-eea686710acb">

### Operating system

macOS

### Browsers

Chrome

**Comment by HessamMosleh** [comment]
Can I take this?

**Comment by Tymmmy** [comment]
@HessamMosleh assigned to you
