### ISSUE TITLE
[BUG] EMail templates have wrong image src

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1584]
### Steps to reproduce

1. Generate either 'verify your email' email or 'forgotten password' email.
2. Check the emails, and see that the images are not correctly loaded

### Expected result

All images in emails should be correctly loaded and displayed.

### Actual result

The Problem is that the image sources use branch names, and not the main branch name, so when the branch got deleted, the images are no longer available.
For example:

Wrong src path:
https://raw.githubusercontent.com/interledger/testnet/1387-test-wallet-new-design-authkyc-pages/packages/wallet/backend/src/email/templates/images/InterledgerTestWallet.png

Correct src path:
https://raw.githubusercontent.com/interledger/testnet/main/packages/wallet/backend/src/email/templates/images/InterledgerTestWallet.png

### Additional context

ToDo
- [ ] verify all email templates and check image src paths
- [ ] replace image src paths to point to main images

### Operating system

macOS

### Browsers

Chrome

**Comment by harshalkh** [comment]
@Tymmmy I am interested to work on this issue. Could you pls assign to me.
