### ISSUE TITLE
[BUG] Delete headless ui deprecated code after recent update

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1616]
### Steps to reproduce

We need to remove <Transition> deprecated code.
<Transition.Child> <Transition.Root>  etc.

### Expected result

Remove deprecated code from all files using it

### Actual result

Code does not contain deprecated tags

### Screenshots or videos
<img width="686" alt="image" src="https://github.com/user-attachments/assets/06c92936-4b35-4d41-9de5-1c1475fe94da">

### Operating system

macOS

### Browsers

Chrome

**Comment by chavdarohit** [comment]
@Tymmmy please assign this to me
