### ISSUE TITLE
[BUG] Error on saving profile details

### ISSUE THREAD

**Issue by adrianboros** [interledger/testnet#1674]
### Steps to reproduce

1. Login into your account 
2. Go to Settings
3. Click edit to edit your account
4. Change/update your name
5. Click on save profile

### Expected result

Userc. profile name update should save

### Actual result

User gets an `Requested path / was not found` error message and the details are not saved

### Screenshots or videos

<img width="1092" alt="Screenshot 2024-10-02 at 14 57 10" src="https://github.com/user-attachments/assets/ed4bdcc0-f298-4e72-8fd2-5074d3e130c1">

### Operating system

macOS

### Browsers

Chrome

**Comment by Tymmmy** [comment]
ToDO:
- [ ] - remove Edit Profile from page
- [ ] - change title to Account Settings 
- [ ] - display only Change password
