### ISSUE TITLE
Refactor into service and controllers for testing purposes

### ISSUE THREAD

**Issue by beniaminmunteanu** [interledger/testnet#194]
Testing the application would benefit of having the code split up in services and controllers.

This way, tests would no longer need to mock req, res, next when calling the actual methods that need to be tested.
They would call the methods with proper, related params.

example:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/111863110/224933282-9d3139f2-37d4-44cc-9d80-c29519d8c09f.png">

**Comment by Tymmmy** [comment]
New backend scaffold is merged into main, new stories will be opened for separate parts of backend
