### ISSUE TITLE
Update Transaction statuses

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#248]
Update the label for transactions in the Transactions list (only Pending is showing right now):
<img width="744" alt="image" src="https://user-images.githubusercontent.com/117268143/231150296-84246128-4a20-4a4b-aa81-03696b73d49f.png">

We also need to add other statuses: Completed, Expired, Failed, Processing, Funding, Sending...

**Comment by raducristianpopa** [comment]
Closed by #200.
