### ISSUE TITLE
Add new ALL Transactions list, add Filters

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#259]
Add a new page for all transactions, no matter the PaymentPointer, no matter currency.
We already have a Transactions list set in place for PaymentPointers.
Should be grouped by date (ex. Revolut)
Add some filters on Transactions list.
For starters Filter by Outgoing/Incoming payment, date, merchant?

If needed and can be done with this story, please also add pagination to list.

**Comment by raducristianpopa** [comment]
Closed by #504.
