### ISSUE TITLE
Back navigation

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#474]
We should implement a back navigation for our pages.
This should be a small arrow representing "Go Back" <-

For example we have the pages Accounts->Payment Pointers->Transactions, and maybe a breadcrumb navigation would help here the users. We can also think on having them on all pages and the back button bringing us back to home page. This would be especially helpful for mobile users, where the main menu is not visible all the time.

The back <= should appear on the very top left side.

**Comment by umeshSinghVerma** [comment]
Hi there, @Tymmmy,

I'm encountering an issue while trying to initialize the project on my local system. Despite following all the instructions outlined in the README.md file, I'm running into the following error when executing pnpm dev:

```
umesh@umesh-Mi-NoteBook-Ultra:~/testnet$ pnpm dev

> @interledger/testnet@1.0.0 dev /home/umesh/testnet
> pnpm localenv:start && concurrently -n 'WALLET,BOUTIQUE' -c blue.bold,red.bold 'pnpm wallet:frontend dev' 'pnpm boutique:frontend dev'


> @interledger/testnet@1.0.0 localenv:start /home/umesh/testnet
> pnpm compose up -d --build


> @interledger/testnet@1.0.0 compose /home/umesh/testnet
> docker compose -f ./docker/dev/docker-compose.yml "up" "-d" "--build"

unknown shorthand flag: 'f' in -f
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/home/umesh/.docker")
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with
                           "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/home/umesh/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/home/umesh/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/home/umesh/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  builder     Manage builds
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.

To get more help with docker, check out our guides at https://docs.docker.com/go/guides/

 ELIFECYCLE  Command failed with exit code 125.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

 It seems that there's an issue with the docker command, specifically with the -f flag. However, I can't seem to pinpoint the exact cause of this problem.

I'd appreciate any guidance or suggestions you might have for resolving this issue. If you need more information or specific details about my setup, please let me know.

Thank you for your help!

**Comment by umeshSinghVerma** [comment]
thanks @Tymmmy there was some problem in my docker I have successfully fixed it and the project is now running in my local environment .
![Screenshot from 2023-10-03 10-50-33](https://github.com/interledger/testnet/assets/119877487/fc9e15ea-582e-478f-ac5f-65d01a789290)

I'm interested in contributing to the project and would like to offer my assistance in resolving this issue. If you don't mind, could you please consider assigning it to me? I'd be more than happy to work on it and help make a positive contribution to the project.

Thank you for considering my request.

Warm regards,

**Comment by umeshSinghVerma** [comment]
Hello @Tymmmy ,

I hope you're doing well. I wanted to provide an update on the project and seek your feedback.

**Screenshot of Back Navigation Button on Login Page:**
![backbutton](https://github.com/interledger/testnet/assets/119877487/2a48b96c-2ac0-496a-9b48-718a174469a6)


Firstly, I've added a sample back navigation button to the login page, and I've attached a screenshot for your review. Please take a look and let me know if it meets the project's requirements, or if any modifications are needed.

Secondly, I've successfully got the frontend running on port 4003. However, I'm facing some challenges with the backend, which is not currently running on port 3003. I'd appreciate your guidance on how to set up and run the backend so that I can navigate to other pages like account and transactions.

Your feedback and assistance are highly valued, and I'm looking forward to your guidance on these matters.

Thank you for your time and support.

Best regards,  
Umesh Singh Verma

**Comment by Tymmmy** [comment]
Hi @umeshSinghVerma  I will assign the issue to you. Did you manage to create an account and also log in? Did you manage to create a sandbox Rapyd account and add the keys into de env variables (docker/dev/.env)? You don't need to fill in every env variable to make what you need work, mainly the RAPYD ones you need for sure.

**Comment by umeshSinghVerma** [comment]
Hello @Tymmmy,

I've been working on setting up an online account successfully. However, I'm facing an issue while trying to create a local account due to a problem with my backend environment. Here's the error message I encountered:

![image](https://github.com/interledger/testnet/assets/119877487/d3ef2e8e-443a-4abe-ae08-a9d10529e123)

Additionally, I've created a sandbox Rapyd account and added the necessary API keys to the `docker/dev/.env` file. You can find the screenshot of my environment configuration here:

![env](https://github.com/interledger/testnet/assets/119877487/7ce36f95-1d16-40d6-b1ec-c5e8cd2a6760)

I've also ensured that I've copied these keys into the `.env.example` file.

Could you please verify if my Rapyd account setup and key integration look correct? Your feedback and guidance on resolving the local account creation issue would be greatly appreciated.

Thank you for your assistance.

Best regards

**Comment by Tymmmy** [comment]
@umeshSinghVerma  .env looks good. Can you check the logs in docker wallet-backend? What does it say there? It should give a bit more details about the issue.

**Comment by umeshSinghVerma** [comment]
Thank you, @Tymmmy! I followed your instructions, and I'm pleased to report that I was able to successfully run the backend and verify the email using the link provided in the docker logs. Please find the attached screenshot for reference. Thanks again for your assistance!

![image](https://github.com/interledger/testnet/assets/119877487/c411da45-1765-4743-ad95-ad056c540fb8)

**Comment by Tymmmy** [comment]
@umeshSinghVerma nice nice, looking forward to your changes.

**Comment by umeshSinghVerma** [comment]
"Hello @Tymmmy , I hope you're doing well. I've submitted a pull request (PR) for your review. Whenever you have some time, I would greatly appreciate it if you could take a look at it. Your feedback and insights would be incredibly valuable. Thank you in advance for your time and consideration!"

**Comment by davoweb3** [comment]
Hi , I am having an issue related to this step, i am able to create an account with a fake email and I collect the data in the wallet/backends docker logs for the verification link, but once I try to login , the login page just doesn't redirects to the KYC page as it is supposed to do. Any help? I appreciate . Thanks 
![image](https://github.com/interledger/testnet/assets/105182325/78f67cda-5159-4533-942b-46ad3d5dfdf2)
