### ISSUE TITLE
Transactions view improvements

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/testnet#543]
- [ ] Use a context for the filters container
- [x] Parse the query parameters with a zod schema
- [ ] Fetch the filters options (accounts and payment pointers) on the client side - remove GSSP
- [x] Button to clear all the filters
- [x] Better pagination component where we are going to display the page numbers as well (`Previous | 1 2 3 ... $lastPage | Next)`
- [x] Allow the user to specify the page size - now it has a default of 10
- [x] Allow ordering from newest to oldest and from oldest to newest by clicking on the `Date` column header
- [x] Use searchParams for transactions list api call

**Comment by Tymmmy** [comment]
- [ ] Use a context for the filters container
- [ ] Fetch the filters options (accounts and payment pointers) on the client side - remove GSSP

The above two requirements were made, on the idea that the requests in the GSSP will always re-request when doing filtering, or pagination.
Further testing shows that GSSP requests for accounts and wallet addresses only happens at the begining, and it does not re-request when filtering, so they will not be done.
