### ISSUE TITLE
Rafiki controller tests 

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#686]
Rafiki controller tests should be created.
Rafiki Service tests can be also added if needed.

**Comment by AniqJaved** [comment]
I would like to work on this issue, but would be requiring some details on it.

**Comment by Tymmmy** [comment]
@AniqJaved  We have some tests already written for controllers, and we would need for wallet/backend/src/ rafiki/controller.ts and service.ts testst written in the same model as for example account or rapyd tests.
Should I assign this to you?

**Comment by AniqJaved** [comment]
Sure, I would love to work on it. But as this is my first time working on something like this I would be requiring help in that regard.

**Comment by Tymmmy** [comment]
Well, I'm not sure what help I can give you just that you need to take all functions one by one, mock the inputs needed, and add tests for the functions as in the examples given above.

**Comment by AniqJaved** [comment]
Sure got it. Also can you let me know where those examples are given ?

**Comment by Tymmmy** [comment]
@AniqJaved I referenced them above in my comment: wallet/backend/src/ rafiki/controller.ts and service.ts tests

**Comment by trupakufi** [comment]
I am working on it. @Tymmmy Can you assign it to me please ?

**Comment by Tymmmy** [comment]
@trupakufi I assigned the issue to you

**Comment by trupakufi** [comment]
Thanks @Tymmmy
