### ISSUE TITLE
Grant interaction improovement 

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#721]
A link to accept or deny grants can be opened from the user many times, and so the Grant can be accepted, declined, accepted, declined etc...multiple times.
We should limit the user to access the link only once, if the Grant was already accepted or declined the user should receive a message that the Grant was already handled and redirected to Grants list.

**Comment by dragosp1011** [comment]
currently the endpoint returning the grant based on interaction id returns only the actions list. `${this.deps.env.AUTH_DOMAIN}/grant/${interactionId}/${nonce}` 
To understand if the interaction took place or not, we will need the grant `state` as well.
so if state is `PENDING` - the page with the choice is displayed
id the state is `GRANTED/REJECTED` - a modal will be shown that the interaction took place and the user will be redirected to grants list page or to the page of the grant if the response will include the grant `id` as well.

@mkurapov @sabineschaller does it make sense to add these fields in the response?

**Comment by raducristianpopa** [comment]
Should we go for a separate GraphQL query to fetch a grant using both `interaction` and `nonce`?

```graphql
grantByInteraction(interaction: String!, nonce: String!): Grant!
```
