### ISSUE TITLE
Implement the Change password feature

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#773]
We started a change password feature, and that can be finished now.
Check ChangePasswordForm for the initial idea.
Update the component according to new Testnet standards.

On the Settings page add a Change password button.
Onclick the Form for change password appears with a new Save password button.
Make the necesarry validations for password checks (already present when registering for an account).
On Save password click, the new password is saved into the database.

**Comment by coder-pink** [comment]
I would like to work on it. Please assign it to me when hacktober is commenced.

**Comment by Cioraz** [comment]
Hey, Im interested in resolving this issue

**Comment by Tymmmy** [comment]
@Cioraz assigned the issue to you

**Comment by Tymmmy** [comment]
@Cioraz any updates on this?

**Comment by Tymmmy** [comment]
Issue is still open if anyone interested for #hacktober

**Comment by trupakufi** [comment]
Here I am.

**Comment by trupakufi** [comment]
@Tymmmy I am trying to solve ir, but I can't test it, and I am having problems to find the controller and the error on this.

**Comment by Tymmmy** [comment]
I am guessing you have the code locally, make sure the docker is running, wallet-backend is running in docker, if you have errors, then the docker logs are the ones that will help us solve the problem. So attach the docker logs from wallet-backend

**Comment by trupakufi** [comment]
> I am guessing you have the code locally, make sure the docker is running, wallet-backend is running in docker, if you have errors, then the docker logs are the ones that will help us solve the problem. So attach the docker logs from wallet-backend

There isn't docker errors. The only error a See is Timeout from the request, that for me it means that the URL passed to the http client is offline.

**Comment by trupakufi** [comment]
![image](https://github.com/interledger/testnet/assets/72455038/eb778ac1-efe5-48fe-80e8-834ba5a76096)

The Docker logs

**Comment by Tymmmy** [comment]
That seems like terminal logs, not docker logs. By docker logs I mean, you go to the Docker, and in the Containers wallet-backend check the logs. It should be something like this:

<img width="798" alt="image" src="https://github.com/interledger/testnet/assets/117268143/b6af8da2-6b6d-4b18-99b3-96901c97ec35">

**Comment by trupakufi** [comment]
Alright, I don't use Docker desktop, only the Docker Engine. How can I see it that well ?

**Comment by trupakufi** [comment]
![image](https://github.com/interledger/testnet/assets/72455038/564991dd-8878-4153-bfd0-1d9edd04b09b)

The Error.

**Comment by trupakufi** [comment]
It is supposed to appear here some log for wallet backend ? 

![image](https://github.com/interledger/testnet/assets/72455038/5bb21afc-8d04-46f5-8e75-da1506a55b9b)

**Comment by Tymmmy** [comment]
You don't have a Sendgrid account that sends email I guess, that's why in env variables the SEND_EMAIL should be set to false. The API key for Sendgrid I can't share, because that is charged. So you will not be able to send password. But the story refers to change password, and not the forgot password. So theoretically tou don't need to send out emails. The change password should be in the Settings menu, and update the pawwsord in the DB in postgres.

**Comment by Tymmmy** [comment]
Logs for wallet-backedn appear in the Logs of the Docker, even if you use only the Docker Engine you should be able to see the logs, I think docker logs wallet-backend command in terminal? I am not sure though...

**Comment by trupakufi** [comment]
> You don't have a Sendgrid account that sends email I guess, that's why in env variables the SEND_EMAIL should be set to false. The API key for Sendgrid I can't share, because that is charged. So you will not be able to send password. But the story refers to change password, and not the forgot password. So theoretically you don't need to send out emails. The change password should be in the Settings menu, and update the password in the DB in postgres.

Yes, I got it now. But, how can I test the change of a password, without have a token to verify and then change it ? I gues the token will be printed at the deps.logger is it right ?

**Comment by trupakufi** [comment]
> Logs for wallet-backedn appear in the Logs of the Docker, even if you use only the Docker Engine you should be able to see the logs, I think docker logs wallet-backend command in terminal? I am not sure though...

So, something went wrong here, I don't see the waller backend logs.

**Comment by Tymmmy** [comment]
So, the user is logged in, so auth has been done already, then the user goes to Settings page, where the form for change password appears if the user clicks on the button. The form requires old password and new password to be set. Then in the backend, because the user is already logged in and you just want to update the old password with the new password for the user that is logged in, you don't need token. Just simple update of password.

**Comment by trupakufi** [comment]
@Tymmmy How can I simmulate the Login ? With wich credencials or how can I log in to enter the settings page and see the form ?

**Comment by Tymmmy** [comment]
you can register with an account with fake email. in .env variables set SEND_EMAIL to false. Go to registration, the KYC is already completed you just have to add a name and click next next. Then when it sais an email has been sent for verification, you go to the docker logs and the link for verification will be there. Now here is the problem if you don't see docker logs :( I suggest trying to fix that problem first. Because after that you can login and see Settings page. But you need that link for verification from wallet-backend docker logs.

**Comment by trupakufi** [comment]
I will try it.

**Comment by trupakufi** [comment]
![image](https://github.com/interledger/testnet/assets/72455038/4a2f4f8d-6f9f-4afc-a661-a598f3e623db)

The error is under boundaries. 😆

**Comment by Tymmmy** [comment]
Do you have the RAPYD keys set up in env variables? Can you send me an example of your env file?

**Comment by trupakufi** [comment]
Yes a Can

env```
RAPYD_ACCESS_KEY=
RAPYD_SECRET_KEY=
RAPYD_SETTLEMENT_EWALLET=
SEND_EMAIL=
FROM_EMAIL=
SENDGRID_API_KEY=
AUTH_IDENTITY_SERVER_SECRET=
RATE_API_KEY=

# commerce env variables
# encoded base 64 private key
PRIVATE_KEY=
KEY_ID=
PAYMENT_POINTER=
´´´

**Comment by Tymmmy** [comment]
the values are empty I see. You need to add values for the first 3 from RAPYD (see README as to how you can do that), then SEND_EMAIL=false. The rest can be empty I think for what you currently need.

**Comment by trupakufi** [comment]
It was the example file. On the real env file I use the Rapyd Values. I'll show you.

**Comment by Tymmmy** [comment]
Please show me your .env file, and make sure you don't try to create a new user with same email as you did before (RAPYD does not allow that, use fake email)

**Comment by trupakufi** [comment]
```env
RAPYD_ACCESS_KEY="rak_EB5F11FE1AB7CDDE677B"
RAPYD_SECRET_KEY="rsk_0fc68b618eab476282c95e4d1cdc17de9a569dbe044607994a8f2ef8164e2be36cd4b4eeca285086"
RAPYD_SETTLEMENT_EWALLET="ewallet_4684051e42a7cc798e53a93927de62a8"
SEND_EMAIL=false
FROM_EMAIL=false
SENDGRID_API_KEY=false
AUTH_IDENTITY_SERVER_SECRET=""
RATE_API_KEY=""

# commerce env variables
# encoded base 64 private key
PRIVATE_KEY=""
KEY_ID=""
PAYMENT_POINTER=""
```

**Comment by NirmitSeta** [comment]
I want to contribute here.

**Comment by trupakufi** [comment]
I am working on. @NirmitSeta

**Comment by trupakufi** [comment]
@Tymmmy  Hey, I Can't keep working on this. I am so busy with school and other stuffs. Can you assign it to another person please ?
