### ISSUE TITLE
Add a copy button next to the payment pointers in the list

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#814]
This is for lazy people :D 
We could add a copy button next to the payment pointers name so people don't have to select and copy :D 
We already use the copy mechanism for Dev Keys in settings, we could add the same button next to the PP name inside ACcount details.

![image](https://github.com/interledger/testnet/assets/117268143/543f5943-af0f-4a80-a06e-678dc98db254)

**Comment by daniloff200** [comment]
hi, @Tymmmy 
Can I pick this one?

**Comment by Tymmmy** [comment]
> hi, @Tymmmy
> Can I pick this one?

Hi @daniloff200  I assigned the story to you :) Have fun with it :)

**Comment by aakash-taneja** [comment]
Hi @Tymmmy can I work on this issue if it is still open

**Comment by Tymmmy** [comment]
@aakash-taneja the issue is still open, but assigned to @daniloff200 . So if we don't receive anything let's say for one more week, then yes I can assign it to you.

**Comment by EdiRomao** [comment]
qual é a linguagem usada no projecto.

**Comment by Tymmmy** [comment]
@EdiRomao we are using for frontend-wallet next js with tailwind, for backend express js.
For boutique we are using simple react.
