### ISSUE TITLE
Payments for really small amounts as well for example 0.01

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#828]
We need to be able to do Payments for really small amounts as well for example 0.01.
I know fees are an issue here, but we need to do a workaround. Or fix the fees to get percentage of the small amount.
Also can we do accounts for assetScale >2?

**Comment by dragosp1011** [comment]
On calculating the quote - one unit will be always extracted form the amount for potential transfer lost. This unit is equivalent to 0.01 for asset scale 2. The minimum send amount is 0.02 in this case.
More details in the comment from `pay` lib: https://github.com/interledgerjs/interledgerjs/blob/fba2dfe8da2e582205632cbbc9433253b7956416/packages/pay/src/index.ts#L385

**Comment by Tymmmy** [comment]
For really small amounts to be sent (especially used in web monetization) we did a quick fix for the ILP Summit 2023.
The fix only allows for USD and assetScale of 9. So some features are hardcoded for now.
We will revisit in the near future.
