### ISSUE TITLE
No hyperlink of the main testnet pic in the Readme.md

### ISSUE THREAD

**Issue by SOBANEJAZ** [interledger/testnet#829]
when we click on the TestNet pic in the documentation we are directed to a new tab with the picture on it.
We can make it a hyperlink that when someone clicks on the picture then he is directed to the features section in the documentation.

Please assign this issue to me for hactoberfest

**Comment by Tymmmy** [comment]
@SOBANEJAZ assigned the issue to you. Thank you for the suggestion.

**Comment by SOBANEJAZ** [comment]
@Tymmmy hey, I have submitted a pull request on this specific [issue](https://github.com/interledger/testnet/pull/838).

**Comment by Tymmmy** [comment]
Solved with merging of PR
