### ISSUE TITLE
Hyperlink to Interledger Website on README.md is incorrect

### ISSUE THREAD

**Issue by aayushborkar14** [interledger/testnet#833]
### Steps to reproduce:
1. Open [README.md](https://github.com/interledger/testnet/blob/main/README.md)
2. Scroll down to [New to Interledger](https://github.com/interledger/testnet/blob/main/README.md#new-to-interledger)
3. Click on [Interledger Website](https://interledger.org/rfcs/0027-interledger-protocol-4/)

### Expected behaviour:
Should open [Interledger Website](https://interledger.org/developers/rfcs/interledger-protocol/)

### Present behaviour:
Opens [Interledger Website](https://interledger.org/rfcs/0027-interledger-protocol-4) which show 404: Not Found
![image](https://github.com/interledger/testnet/assets/30978331/96d070ad-06f3-4fdd-919a-07c2f6b7f673)

**Comment by aayushborkar14** [comment]
Can you assign me this issue for Hactoberfest?

**Comment by Tymmmy** [comment]
@aayushborkar14  assigned the issue to you, thank you for nooticing this bug.
