### ISSUE TITLE
Request payment error

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#861]
Create an account with RON currency, and one with EUR currency.
Request 100 RON from the account, and try sending/paying it with the EUR account.
Even if you have enough money, and everything should be ok we have an error.
<img width="771" alt="image" src="https://github.com/interledger/testnet/assets/117268143/9df7d0ce-2e28-4128-b7df-15dad335ef5c">

Same happens for HUF or DKK.

EUR USD GBP work.

**Comment by AvinashReddy19** [comment]
Is it still open @Tymmmy if yes I can resolve this issue

**Comment by Tymmmy** [comment]
@AvinashReddy19 you can see there is a branch attached to it, with a PR, and that already solves the issue. It needs approve and merging. This is not part of the #hacktober ticket list.

**Comment by AvinashReddy19** [comment]
Label of this issue is still open and also branch didn't yet merged so that's why I commented
