### ISSUE TITLE
Fix overflow in developer keys page

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/testnet#891]
As the list currently has the class `overflow-hidden`, it doesn't display all payment pointers. We should change it to `overflow-scroll px-2`

https://github.com/interledger/testnet/blob/f249dfd4009c7010716ff948728c900044bcf809/packages/wallet/frontend/src/components/settings/DeveloperKeys.tsx#L106

**Comment by cyberdad68** [comment]
i would like to work on this issue,Could you assign me this.

**Comment by raducristianpopa** [comment]
@cyberdad68 I've assigned the issue to you.

**Comment by cyberdad68** [comment]
@raducristianpopa I have made the required changes. Please review it once, Let me know if any misinterpretations.
