### ISSUE TITLE
[WM] Display WM Payment Pointers in separate list

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#899]
- add a new menu item - Web Monetization
- display in the new page a list of payment pointers used for WM
- the list will be similar to the Accounts 'normal' PPs for now

**Comment by trupakufi** [comment]
I want to work on it can You assign it to me Please ?

**Comment by Tymmmy** [comment]
@trupakufi this is an urgent issue, not related to #hacktober, so the team will work on this ASAP, as we understand the logic and business behind it already. Thank you for your interest.

**Comment by trupakufi** [comment]
Yes, I am.

**Comment by Tymmmy** [comment]
@trupakufi please comment on that story then, so I can assign it to you. Otherwise Github does not find you in the list.

**Comment by raducristianpopa** [comment]
Closed by #902.
